### ISSUE TITLE
Query - How to build locally

### ISSUE THREAD

**Issue by netmindz** [geoffdavis/esphome-mitsubishiheatpump#115]
I'm trying to write my own custom component following your example.

Do you have a platformio.ini file that can be used to compile the code locally so I don't need to keep pushing commits to git to then try and run the build of the full image in ESPHome?

**Comment by echavet** [comment]
old message but actually if you want to do that you just have to get the sources from rep in a local directory and use:
```
external_components:
 - source:
     type: local
     path: components
``` 
in place of 
```
external_components:
 - source: github://...


```
