### ISSUE TITLE
Add DRY mode

### ISSUE THREAD

**Issue by RikBast** [geoffdavis/esphome-mitsubishiheatpump#137]
Hi,

Is it possible to add the DRY mode to this?
That would be awesome,  horizontal vane is in make I see.

thx,
Rik

**Comment by jpgnz** [comment]
Dry mode is already supported by the underlying SwiCago/HeatPump library, you may have to configure it manually:

```
climate:
  - platform: mitsubishi_heatpump
    name: "${friendly_name}"
    supports:
      mode: [COOL, HEAT, DRY, FAN_ONLY]
```

![image](https://github.com/geoffdavis/esphome-mitsubishiheatpump/assets/1733900/5eba067d-1999-4476-acfe-cf6ed464da11)
