### ISSUE TITLE
esphome 2024.6.0 changed the definition of HARDWARE_UART_TO_SERIAL

### ISSUE THREAD

**Issue by sanjay900** [geoffdavis/esphome-mitsubishiheatpump#152]
Support for the rp2040 was merged into esphome, which changed the definition of that dictionary and its no longer possible to specify UART2 on the esp32 without a compilation error.

Ended up swapping to https://github.com/echavet/MitsubishiCN105ESPHome though as i was having problems with this component not receiving the temperature from my unit, which was resolved when i swapped.

**Comment by pomah86** [comment]
I would prefer not to swap, any chance this will be fixed?

**Comment by sanjay900** [comment]
Shouldn't be too hard to fix, just need to change that line to the following and import `PLATFORM_ESP8266`
```
serial = HARDWARE_UART_TO_SERIAL[PLATFORM_ESP8266][config[CONF_HARDWARE_UART]]
```

**Comment by Aresitoo** [comment]
Got the same problem here.

But dont understand what i need to modify in my code go make it work ( total noob sorry ) 

![Screenshot_20240620-161450](https://github.com/geoffdavis/esphome-mitsubishiheatpump/assets/85060696/9357f0f5-5b1b-4221-b4bd-483cf77bd792)

**Comment by ghisch** [comment]
@sanjay900 made a PR following your recommendation, do not hesitate to review

@Aresitoo can't be fixed from your config file, need to be changed in the code

**Comment by iddiek** [comment]
same problem with a esp8266 board
  File "/data/external_components/3b4567cc/components/mitsubishi_heatpump/climate.py", line 66, in to_code
    serial = HARDWARE_UART_TO_SERIAL[config[CONF_HARDWARE_UART]]
             ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'UART0'

**Comment by Aresitoo** [comment]
@ghisch So meaning just wait till a fix of the code comes out ? ( sorry I'm zero in code HA and Esphome )

**Comment by ghisch** [comment]
@Aresitoo Yes

**Comment by sanjay900** [comment]
you could probably just change the external component to point to that PR and see if it works

**Comment by rkboni** [comment]
It definitely built, but the first one I updated has not come back online yet (and it's been long enough that I suspect the change either isn't right, or needs more configuration.

Here's my config:

```
substitutions:
  name: "basement-minisplit"
  friendly_name: Basement MiniSplit
  
esphome:
  name: ${name}

esp8266:
  board: d1_mini

# Enable logging
logger:
  # ESP8266 only - disable serial port logging, as the HeatPump component
  # needs the sole hardware UART on the ESP8266
  baud_rate: 0

# Enable Home Assistant API
api:

ota:
  platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: <static-ip>
    gateway: <gateway-ip>
    subnet: <subnet>
    dns1: <dns-ip>

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback"
    password: !secret fallback_password

captive_portal:

# Enable Web server.
web_server:
  port: 80

  # Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ${name} ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${name} IP
    ssid:
      name: ${name} SSID
    bssid:
      name: ${name} BSSID

# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: ${name} Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: ${name} WiFi Signal
    update_interval: 60s

switch:
  - platform: restart
    name: "${friendly_name} Restart"

external_components:
  - source: github://ghisch/esphome-mitsubishiheatpump@patch-1

climate:
  - platform: mitsubishi_heatpump
    name: "${friendly_name}"
```
