### ISSUE TITLE
Repeated disconnections from Home Assistant

### ISSUE THREAD

**Issue by drogfild** [geoffdavis/esphome-mitsubishiheatpump#23]
Hi,

First thanks for all the great work you have put into this! But for some reason I'm unable to get this running properly. I get repeated Home Assistant disconnections and I don't find a reason for it. It's connecting, updating other values to HA (but client component is missing details) but then it disconnects. After few seconds it reconnects and same happens again.

I have now tried two different ESP32 boards connected to CN105 and also without connection to heatpump. It builds up just fine without problems. First I was with beta version of ESPHome 1.15.x and now with official release 1.15.2. 

Could you check and advice how to troubleshoot this? Is there something missing in my configuration? Or how to find the real issue in this?

Log:
```
[12:45:11][D][time:040]: Synchronized time: Wed Sep 23 12:45:11 2020
[12:45:12][D][api:067]: Disconnecting Home Assistant 0.115.2 (192.168.1.240)
[12:45:12][D][api.connection:604]: Client 'Home Assistant 0.115.2 (192.168.1.240)' connected successfully!
[12:45:12][D][time:040]: Synchronized time: Wed Sep 23 12:45:12 2020
[12:45:12][D][api:067]: Disconnecting Home Assistant 0.115.2 (192.168.1.240)
[12:45:12][D][api.connection:604]: Client 'Home Assistant 0.115.2 (192.168.1.240)' connected successfully!
[12:45:12][D][time:040]: Synchronized time: Wed Sep 23 12:45:12 2020
[12:45:12][D][api:067]: Disconnecting Home Assistant 0.115.2 (192.168.1.240)
[12:45:12][D][api.connection:604]: Client 'Home Assistant 0.115.2 (192.168.1.240)' connected successfully!
[12:45:13][D][time:040]: Synchronized time: Wed Sep 23 12:45:12 2020
[12:45:13][D][api:067]: Disconnecting Home Assistant 0.115.2 (192.168.1.240)
[12:45:13][D][api.connection:604]: Client 'Home Assistant 0.115.2 (192.168.1.240)' connected successfully!
```

Short part of Very Verbose log:
```
[21:26:35][VV][api.service:131]: send_text_sensor_state_response: TextSensorStateResponse {
  key: 2119287227
  state: '1.15.0b4 Sep 12 2020, 21:24:38'
  missing_state: NO
}
[21:26:35][VV][api.service:131]: send_text_sensor_state_response: TextSensorStateResponse {
  key: 1752637618
  state: '192.168.1.248'
  missing_state: NO
}
[21:26:35][VV][api.service:181]: send_climate_state_response: ClimateStateResponse {
  key: 1293927233
  mode: CLIMATE_MODE_OFF
  current_temperature: nan
  target_temperature: -1.69474e+38
  target_temperature_low: 0
  target_temperature_high: 0
  away: NO
  action: CLIMATE_ACTION_OFF
  fan_mode: UNKNOWN
  swing_mode: UNKNOWN
}
[21:26:35][D][api:067]: Disconnecting Home Assistant 0.114.4 (192.168.1.240)
[21:26:38][VV][api.service:192]: on_hello_request: HelloRequest {
  client_info: 'Home Assistant 0.114.4'
}
[21:26:38][V][api.connection:588]: Hello from client: 'Home Assistant 0.114.4 (192.168.1.240)'
[21:26:38][VV][api.service:012]: send_hello_response: HelloResponse {
  api_version_major: 1
  api_version_minor: 3
  server_info: 'mitsubishiheatpump (esphome v1.15.0b4)'
}
```
Notice how target_temperature is weird value at least in the log. And disconnection happens right after that. I didn't find any interesting logs from Home Assistant side that would correlate with these.

My code:
```
substitutions:
  devicename: mitsubishiheatpump
  upper_devicename: MitsubishiHeatpump
  description: https://github.com/geoffdavis/esphome-mitsubishiheatpump

# cd src
# git clone https://github.com/geoffdavis/esphome-mitsubishiheatpump.git


esphome:
  name: $devicename
  platform: ESP32
  board: esp-wrover-kit
  comment: $description
  
  libraries:
    - SwiCago/HeatPump
# tried this library also, but that didn't compile without errors and seems to be included in SwiCago now
#    - https://github.com/geoffdavis/HeatPump#init_fix  

  includes:
    - src/esphome-mitsubishiheatpump

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $devicename
    password: !secret esphome_backup_ap_password

#captive_portal:

# Enable logging, but disable for uart
logger:
  baud_rate: 0
#  level: VERY_VERBOSE

# Web server can be removed after enabling HA API
#web_server: 
#  port: 80

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

ota:
  password: !secret ota_password
  id: otapw

sensor:
  - platform: uptime
    name: uptime
  - platform: wifi_signal
    name: wifi_signal
    update_interval: 120s


text_sensor:
  - platform: version
    name: version
  - platform: wifi_info
    ip_address:
      name: ip

climate:
  # ESP32 only - change &Serial to &Serial1 or &Serial2 and remove the
  # logging:baud_rate above to allow the built-in UART0 to function for
  # logging.
  - platform: custom
    lambda: |-
      auto my_heatpump = new MitsubishiHeatPump(&Serial);
      App.register_component(my_heatpump);
      return {my_heatpump};
    climates:
      - name: "Heat Pump"

```
I have also tried &Serial1 and &Serial2 but those didn't have any effect on the issue.
