### ISSUE TITLE
Losing Mitsu connection after firmware update

### ISSUE THREAD

**Issue by earwin** [geoffdavis/esphome-mitsubishiheatpump#49]
I'm running ESPHome on a random D1 Mini Pro.
Every time I update it, rebuild the firmware, and upload to the controller, it loses the ability to communicate with Mitsu.
A manual reset at this point always fixes things.

I bodged up a switch to do it, like
```yaml
switch:
  - platform: restart
    name: Mitsubishi AC Controller Reset
```
so it's no longer a problem. And I can maybe later add some hook to firmware update, so I don't have to remember.

But raising this here in case anyone has ideas or wants to share their experience.
