### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by javilopezalarcon** [geoffdavis/esphome-mitsubishiheatpump#58]
Good morning, I have changed esphome to their repository, since the community repository will be obsolete. I have given to update the wemos that I use for the air conditioning and I get the error that I told you next. the wemos works well, but I imagine that for future updates it could fail and I don't know how to correct it, nor could I clear it myself. A greeting

`src/esphome/components/mitsubishi_heatpump/espmhp.cpp: In member function 'virtual void MitsubishiHeatPump::setup()':
src/esphome/components/mitsubishi_heatpump/espmhp.cpp:459:56: error: no matching function for call to 'HeatPump::connect(HardwareSerial*, int&)'
  459 |     if (hp->connect(this->get_hw_serial_(), this->baud_)) {
      |                                                        ^
In file included from src/esphome/components/mitsubishi_heatpump/espmhp.h:23,
                 from src/esphome.h:29,
                 from src/esphome/components/mitsubishi_heatpump/espmhp.h:20,
                 from src/esphome/components/mitsubishi_heatpump/espmhp.cpp:20:
/data/aire-acondicionado/.piolibdeps/aire-acondicionado/HeatPump/src/HeatPump.h:237:10: note: candidate: 'bool HeatPump::connect(HardwareSerial*)'
  237 |     bool connect(HardwareSerial *serial);
      |          ^~~~~~~
/data/aire-acondicionado/.piolibdeps/aire-acondicionado/HeatPump/src/HeatPump.h:237:10: note:   candidate expects 1 argument, 2 provided
/data/aire-acondicionado/.piolibdeps/aire-acondicionado/HeatPump/src/HeatPump.h:238:10: note: candidate: 'bool HeatPump::connect(HardwareSerial*, int, int)'
  238 |     bool connect(HardwareSerial *serial, int rx, int tx);
      |          ^~~~~~~
/data/aire-acondicionado/.piolibdeps/aire-acondicionado/HeatPump/src/HeatPump.h:238:10: note:   candidate expects 3 arguments, 2 provided
/data/aire-acondicionado/.piolibdeps/aire-acondicionado/HeatPump/src/HeatPump.h:239:10: note: candidate: 'bool HeatPump::connect(HardwareSerial*, int, int, int)'
  239 |     bool connect(HardwareSerial *serial, int bitrate, int rx, int tx);
      |          ^~~~~~~
/data/aire-acondicionado/.piolibdeps/aire-acondicionado/HeatPump/src/HeatPump.h:239:10: note:   candidate expects 4 arguments, 2 provided
Compiling /data/aire-acondicionado/.pioenvs/aire-acondicionado/src/esphome/core/controller.cpp.o
*** [/data/aire-acondicionado/.pioenvs/aire-acondicionado/src/esphome/components/mitsubishi_heatpump/espmhp.cpp.o] Error 1
========================= [FAILED] Took 17.18 seconds =========================`

I also leave you my configuration in case it helps, but I already said, I have it working perfectly, it only gives me the error when clicking update now

 ````
esphome:

  name: aire-acondicionado
  platform: ESP8266
  board: d1_mini

# Enable Home Assistant API
api:
  password: !secret api_password
  services:
    - service: set_remote_temperature
      variables:
        temperature: float
      then:
        - lambda: 'id(aire).set_remote_temperature(temperature);'
      
    - service: use_internal_temperature
      then:
        - lambda: 'id(aire).set_remote_temperature(0);'
    
  #reboot_timeout: 2min
  
ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  use_address: aire.lan

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Aire Acondicionado"
    password: "rfh9RiL5ZNy9"

mdns:
  disabled: true

captive_portal:

# Enable logging
logger:
  # ESP8266 only - disable serial port logging, as the HeatPump component
  # needs the sole hardware UART on the ESP8266
  baud_rate: 0


# Enable Web server.
web_server:
  port: 80

  # Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information.
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: Aire Acondicionado ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: Aire Acondicionado IP
    ssid:
      name: Aire Acondicionado SSID
    bssid:
      name: Aire Acondicionado BSSID


external_components:
  - source: github://geoffdavis/esphome-mitsubishiheatpump

climate:
  - platform: mitsubishi_heatpump
    name: "Aire Acondicionado"
    id: aire
    #baud_rate: 9600
    # ESP32 only - change UART0 to UART1 or UART2 and remove the
    # logging:baud_rate above to allow the built-in UART0 to function for
    # logging.
    hardware_uart: UART0
    
    update_interval: 500ms
# Sensors with general information.
sensor:
  # Uptime sensor.
  - platform: uptime
    name: Aire Acondicionado Uptime

  # WiFi Signal sensor.
  - platform: wifi_signal
    name: Aire Acondicionado WiFi Signal
    update_interval: 60s
    
  - platform: homeassistant
    name: "Temperatura Media de Casa"
    entity_id: sensor.temperatura_media_casa
    on_value:
      then:
        - lambda: 'id(aire).set_remote_temperature(x);'
    force_update: true
    accuracy_decimals: 2`
```

Sorry for my English, I'm Spanish and I use a translator
